### ISSUE TITLE
[English]: Store purchase confirmation

### ISSUE THREAD

**Issue by Greaver** [WoW-CMS/support#12]
### What operating system are you using?

Linux

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

Dedicated server

### Which emulator are you using and which version?

TrinityCore

### Describe the bug

No confirmation is given after buying things from the store.
Additional info: Apologies, couldve been more precise. Buying things work, theres just not any kind of indication for the process to complete, just goes to an empty page.

### How can I reproduce the problem?

Add an item to cart and buy it.

**Comment by pangolp** [comment]
Did you check the soap configuration? Log into your domain, and first verify that communication via soap is working. To do this, if your domain is: www.domain.com, login with a level 3 user, administrator, and in the URL enter: www.domain.com/en/admin/checksoap

If you get a `.server info` message, then the soap configuration is fine. If, on the other hand, you do not receive a message with this information, the problem is in the soap configuration.

**Comment by newrage** [comment]
SoapFault exception: [HTTP] Could not connect to host in

**Comment by pangolp** [comment]
> SoapFault exception: [HTTP] Could not connect to host in

You have to enable `soap` in the emulator. And then you have to install `php_soap` in the hosting, or in the place where you have the CMS, until you have the configuration working. If that doesn't work, you won't get the stuff you buy.

**Comment by Greaver** [comment]
Turns out this was caused by me, myself and my browser addons :)
