### ISSUE TITLE
[English support]: Store - BlizzCMS 1.0.7.5

### ISSUE THREAD

**Issue by noxcis12** [WoW-CMS/support#5]
# Wow-CMS English support

### What operating system are you using?
- [x] Linux

### What version of PHP do you use?
- [x] PHP 7.x

### Where did you get the CMS code?
- [x] Github

### Where are you trying to install the CMS?
- [x] VPS

### Which emulator are you using and which version?
- [x] AzerothCore

### Describe the bug
- When I want to make a purchase on the store I only have this white box that appears

### How can I reproduce the problem?

1.Log in on your account
2.add donator points
3.Go store and purchase 1 item
4. http://artika-serveur.com/fr/store/mount
5. Logs for test  name : acore , pass : Test123

### Screenshots

![1](https://user-images.githubusercontent.com/85730526/121673037-c8fcd600-cab0-11eb-82bd-ca959e204439.png)

**Comment by pangolp** [comment]
Hello, the problem is the apostrophe, that is, those words that use **'**. In other words, items containing this format cannot be used for the time being. The problem is that the CMS, interprets that when using that, the name ends there, so it stops working. Rename the items, and you will see that you will not have problems.

**Comment by noxcis12** [comment]
thank you that solved my problem

**Comment by pangolp** [comment]
You're welcome.
